modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "EpiaC9"
description = """
Cobblemon No Man's Land adds procedurally generated dungeon encounters
for Cobblemon, including trainers, raid bosses, alpha Pokémon,
trial spawners, vaults, tiered dungeon portals, and custom encounters.
"""

[[mixins]]
config = "cobblemonnml.mixins.json"
requiredMods = ["yagm"]

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[${neo_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "cobblemon"
type = "required"
versionRange = "[1.7.3,2.0.0)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "kotlinforforge"
type = "required"
versionRange = "[5.12.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "geckolib"
type = "required"
versionRange = "[4.9.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "cobblemonraiddens"
type = "required"
versionRange = "[0.11.6,0.12.0)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "architectury"
type = "required"
versionRange = "[13.0.11,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "rctapi"
type = "required"
versionRange = "[0.15.2-beta,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "tbcs"
type = "required"
versionRange = "[0.14.1-beta,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "easy_npc"
type = "required"
versionRange = ""
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "easy_npc_bundle"
type = "required"
versionRange = "[7.6.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "easy_npc_config_ui"
type = "required"
versionRange = "[7.6.0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "cobblemontrialsedition"
type = "required"
versionRange = "[2.1.0,3.0.0)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "yagm"
type = "required"
versionRange = "[0.1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "octolib"
type = "required"
versionRange = "[0.6.2,1.0.0)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemonnml]]
modId="fightorflight"
type="required"
versionRange="[0.10.9,)"
ordering="AFTER"
side="BOTH"
