package net.epiac9.cobblemonnml.battle.action.effect;

public enum ActionBattleStatusApplication {
    CINDERS_APPLIED,
    BURN_APPLIED,
    BURN_REFRESHED,
    FREEZE_APPLIED,
    FROSTBITE_APPLIED,
    FROSTBITE_REFRESHED,
    POISON_APPLIED,
    TOXIC_1_APPLIED,
    TOXIC_2_APPLIED,
    TOXIC_3_APPLIED,
    TOXIC_3_REAPPLIED,
    PARALYSIS_APPLIED,
    PARALYSIS_REFRESHED,
    DROWSINESS_APPLIED,
    DROWSINESS_SHORTENED,
    DROWSINESS_BLOCKED,
    SLEEP_APPLIED,
    SLEEP_WOKE,
    CONFUSION_APPLIED,
    CONFUSION_REFRESHED,
    EVASION_APPLIED,
    EVASION_REFRESHED
}
